export const FETCH_IMAGE_START = "FETCH_IMAGE_START";
export const FETCH_IMAGE_SUCCES = "FETCH_IMAGE_SUCCES";
export const FETCH_IMAGE_FAILURE = "FETCH_IMAGE_FAILURE";

export const ADD_IMAGE_SUCCES = "ADD_IMAGE_SUCCES";

export const ADD_A_TAG = "ADD_A_TAG";

export const CLEAR_STORAGE = "CLEAR_STORAGE";

export const MULTI_IMAGE_SUCCES = "MULTI_IMAGE_SUCCES";

export const ADD_MULTY_TAGS = "ADD_MULTY_TAGS";
